import { TemplateMetadata } from "website-core";

export const FORTAX_METADATA: TemplateMetadata = {
  id: "fortax",
  name: "Fortax Financial Advisory",
  tagline: "Modern Warm Cream & Dark Cyan Financial Advisor & Tax Advisory Template",
  description: "Elegantly structured financial advisory template with warm cream hero, multi-tag service cards, and concierge lead banner.",
  category: "Modern",
  defaultTheme: {
    primaryColor: "#025a70",
    accentColor: "#e69526",
    backgroundColor: "#ffffff",
    surfaceColor: "#faf8f5",
    textColor: "#172b38",
    fontFamily: "Playfair Display",
    borderRadius: "lg",
  },
  features: [
    "Warm Cream Hero with Advisor Portrait",
    "5 Specialized Service Matrix Cards",
    "3-Tier Transparent Pricing Packages",
    "Concierge Advisory Desk & Lead Capture",
  ],
  sections: [
    {
      id: "hero",
      type: "hero",
      label: "Hero Banner",
      description: "Warm cream header, advisor portrait card and primary CTAs",
      editorKey: "hero",
      required: true,
      defaultEnabled: true,
    },
    {
      id: "services",
      type: "services",
      label: "Services & Practice Areas",
      description: "Specialized service cards, pricing tiers and scope matrices",
      editorKey: "services",
      defaultEnabled: true,
    },
    {
      id: "tax-calendar",
      type: "tax-calendar",
      label: "Statutory Due Dates",
      description: "Structured compliance and statutory tax calendar",
      editorKey: "tax-calendar",
      defaultEnabled: true,
    },
    {
      id: "calculators",
      type: "calculators",
      label: "Financial Calculators",
      description: "Old vs new tax regime, GST ITC and advance tax tools",
      editorKey: "calculators",
      defaultEnabled: true,
    },
    {
      id: "testimonials",
      type: "testimonials",
      label: "Client Endorsements",
      description: "Executive and business owner testimonials",
      editorKey: "testimonials",
      defaultEnabled: true,
    },
    {
      id: "cta",
      type: "cta",
      label: "Call to Action Banner",
      description: "Concierge advisory consultation banner",
      editorKey: "cta",
      defaultEnabled: true,
    },
    {
      id: "contact",
      type: "contact",
      label: "Contact Information Desk",
      description: "Lead form, branch address, contact channels & office directions",
      editorKey: "contact",
      required: true,
      defaultEnabled: true,
    },
  ],
};

