import { TemplateMetadata } from "website-core";

export const APEX_CORPORATE_METADATA: TemplateMetadata = {
  id: "apex-corporate",
  name: "Apex Corporate",
  tagline: "Authoritative & Polished for Established Practices",
  description: "Deep emerald and slate tones with authoritative typography, structured service grids, and compliance tickers.",
  category: "Corporate",
  defaultTheme: {
    primaryColor: "#0f6e56",
    accentColor: "#1d9e75",
    backgroundColor: "#ffffff",
    surfaceColor: "#f9fafb",
    textColor: "#111827",
    fontFamily: "Space Grotesk",
    borderRadius: "md",
  },
  features: ["Standard Professional Disclaimer", "Tax Calendar Due Date Monitor", "Direct WhatsApp CTA", "Service Scope Grid"],
  sections: [
    {
      id: "hero",
      type: "hero",
      label: "Hero Banner",
      description: "Headline, CTA Buttons & Framed Hero Imagery",
      editorKey: "hero",
      required: true,
      defaultEnabled: true,
    },
    {
      id: "services",
      type: "services",
      label: "Services & Practice Areas",
      description: "Practice area directory and 8 specialized desk photo tiles",
      editorKey: "services",
      defaultEnabled: true,
    },
    {
      id: "tax-calendar",
      type: "tax-calendar",
      label: "Statutory Due Dates",
      description: "Upcoming GST, TDS, and ROC statutory deadlines",
      editorKey: "tax-calendar",
      defaultEnabled: true,
    },
    {
      id: "calculators",
      type: "calculators",
      label: "Financial Calculators",
      description: "GST liability, tax regime comparator and loan tools",
      editorKey: "calculators",
      defaultEnabled: true,
    },
    {
      id: "testimonials",
      type: "testimonials",
      label: "Client Endorsements",
      description: "ICAI-compliant verified engagement feedback summaries",
      editorKey: "testimonials",
      defaultEnabled: true,
    },
    {
      id: "cta",
      type: "cta",
      label: "Call to Action Banner",
      description: "High-impact consultation booking strip",
      editorKey: "cta",
      defaultEnabled: true,
    },
    {
      id: "contact",
      type: "contact",
      label: "Contact Information Desk",
      description: "Lead form, branch address, contact channels & office directions",
      editorKey: "contact",
      required: true,
      defaultEnabled: true,
    },
  ],
};

