import { TemplateMetadata } from "website-core";

export const TRUST_CLASSIC_METADATA: TemplateMetadata = {
  id: "trust-classic",
  name: "Trust & Traditional",
  tagline: "Timeless Prestige for Senior Advisory & Audit Firms",
  description: "Classic navy and warm brass styling emphasizing partner credentials, history, and statutory audit integrity.",
  category: "Classic",
  defaultTheme: {
    primaryColor: "#1e3a8a",
    accentColor: "#b45309",
    backgroundColor: "#ffffff",
    surfaceColor: "#f8fafc",
    textColor: "#1e293b",
    fontFamily: "Playfair Display",
    borderRadius: "sm",
  },
  features: ["Partner Profile Spotlight", "Prestige Serif Typography", "Formal Audit Case Studies", "Clean Topbar Notice"],
  sections: [
    {
      id: "hero",
      type: "hero",
      label: "Hero Banner",
      description: "Centered prestige headline, founding credentials & framed portrait",
      editorKey: "hero",
      required: true,
      defaultEnabled: true,
    },
    {
      id: "services",
      type: "services",
      label: "Services & Practice Areas",
      description: "Two-column detailed statutory audit and practice areas",
      editorKey: "services",
      defaultEnabled: true,
    },
    {
      id: "tax-calendar",
      type: "tax-calendar",
      label: "Statutory Due Dates",
      description: "Classic standalone tax calendar and due date monitor",
      editorKey: "tax-calendar",
      defaultEnabled: true,
    },
    {
      id: "calculators",
      type: "calculators",
      label: "Financial Calculators",
      description: "Statutory and tax computation tools",
      editorKey: "calculators",
      defaultEnabled: true,
    },
    {
      id: "testimonials",
      type: "testimonials",
      label: "Client Endorsements",
      description: "Prestige blockquote testimonials from institutional clients",
      editorKey: "testimonials",
      defaultEnabled: true,
    },
    {
      id: "cta",
      type: "cta",
      label: "Call to Action Banner",
      description: "Advisory consultation appointment banner",
      editorKey: "cta",
      defaultEnabled: true,
    },
    {
      id: "contact",
      type: "contact",
      label: "Contact Information Desk",
      description: "Lead form, branch address, contact channels & office directions",
      editorKey: "contact",
      required: true,
      defaultEnabled: true,
    },
  ],
};

