import { TemplateMetadata } from "website-core";

export const FINTECH_MODERN_METADATA: TemplateMetadata = {
  id: "fintech-modern",
  name: "FinTech Modern",
  tagline: "Dynamic, Calculator-First for Fast-Growing Startups",
  description: "Electric sky and royal accents with modern stats, interactive calculators, and high-conversion consultation blocks.",
  category: "Modern",
  defaultTheme: {
    primaryColor: "#0284c7",
    accentColor: "#38bdf8",
    backgroundColor: "#ffffff",
    surfaceColor: "#f0f9ff",
    textColor: "#0f172a",
    fontFamily: "Inter",
    borderRadius: "lg",
  },
  features: ["Embedded Tax Calculators", "Interactive Feature Grid", "Lead Stats Showcase", "Modern Glass Header"],
  sections: [
    {
      id: "hero",
      type: "hero",
      label: "Hero Banner",
      description: "Hero headline, CTA buttons, metrics badge & photo card",
      editorKey: "hero",
      required: true,
      defaultEnabled: true,
    },
    {
      id: "services",
      type: "services",
      label: "Services & Practice Areas",
      description: "Modern cards for fast-growing startup compliance scopes",
      editorKey: "services",
      defaultEnabled: true,
    },
    {
      id: "tax-calendar",
      type: "tax-calendar",
      label: "Statutory Due Dates",
      description: "Quarterly and monthly statutory tax deadlines",
      editorKey: "tax-calendar",
      defaultEnabled: true,
    },
    {
      id: "calculators",
      type: "calculators",
      label: "Financial Calculators",
      description: "Interactive GST liability, tax regime comparator and loan calculators",
      editorKey: "calculators",
      defaultEnabled: true,
    },
    {
      id: "testimonials",
      type: "testimonials",
      label: "Client Endorsements",
      description: "Startup founder & business executive feedback summaries",
      editorKey: "testimonials",
      defaultEnabled: true,
    },
    {
      id: "cta",
      type: "cta",
      label: "Call to Action Banner",
      description: "Consultation call conversion strip",
      editorKey: "cta",
      defaultEnabled: true,
    },
    {
      id: "contact",
      type: "contact",
      label: "Contact Information Desk",
      description: "Lead form, branch address, contact channels & office directions",
      editorKey: "contact",
      required: true,
      defaultEnabled: true,
    },
  ],
};

