import { TemplateMetadata } from "website-core";

export const MINIMAL_STUDIO_METADATA: TemplateMetadata = {
  id: "minimal-studio",
  name: "Minimalist Studio",
  tagline: "High-Contrast, Content-Centric Boutique Consulting",
  description: "Monochrome elegance with high-contrast typography and focus on advisory value propositions.",
  category: "Minimal",
  defaultTheme: {
    primaryColor: "#18181b",
    accentColor: "#52525b",
    backgroundColor: "#fafafa",
    surfaceColor: "#ffffff",
    textColor: "#09090b",
    fontFamily: "Plus Jakarta Sans",
    borderRadius: "none",
  },
  features: ["Ultra Clean Layout", "High-Contrast Typography", "Distraction-Free Consultation Funnel", "Minimal Footer"],
  sections: [
    {
      id: "hero",
      type: "hero",
      label: "Hero Banner",
      description: "Monochrome headline, mission statement & minimal photo showcase",
      editorKey: "hero",
      required: true,
      defaultEnabled: true,
    },
    {
      id: "services",
      type: "services",
      label: "Services & Practice Areas",
      description: "Clean minimalist advisory list and scope descriptions",
      editorKey: "services",
      defaultEnabled: true,
    },
    {
      id: "tax-calendar",
      type: "tax-calendar",
      label: "Statutory Due Dates",
      description: "High-contrast compliance date tracker",
      editorKey: "tax-calendar",
      defaultEnabled: true,
    },
    {
      id: "calculators",
      type: "calculators",
      label: "Financial Calculators",
      description: "Minimalist financial estimators and calculators",
      editorKey: "calculators",
      defaultEnabled: true,
    },
    {
      id: "testimonials",
      type: "testimonials",
      label: "Client Endorsements",
      description: "Minimal quote reviews from verified clients",
      editorKey: "testimonials",
      defaultEnabled: true,
    },
    {
      id: "cta",
      type: "cta",
      label: "Call to Action Banner",
      description: "Clean text-focused engagement banner",
      editorKey: "cta",
      defaultEnabled: true,
    },
    {
      id: "contact",
      type: "contact",
      label: "Contact Information Desk",
      description: "Lead form, branch address, contact channels & office directions",
      editorKey: "contact",
      required: true,
      defaultEnabled: true,
    },
  ],
};

