import { TemplateMetadata } from "website-core";

export const EASY_FILINGS_METADATA: TemplateMetadata = {
  id: "easy-filings",
  name: "EasyFilings Portal",
  tagline: "High-Conversion Compliance & Advisory Portal for Growth Practices",
  description: "Dynamic portal with floating consultation desk, trust metrics strip, filterable service catalog, and compliance due date monitor.",
  category: "Modern",
  defaultTheme: {
    primaryColor: "#00635a",
    accentColor: "#10b981",
    backgroundColor: "#ffffff",
    surfaceColor: "#f8fafc",
    textColor: "#0f172a",
    fontFamily: "Space Grotesk",
    borderRadius: "md",
  },
  features: [
    "Interactive Expert Callback Card",
    "Filterable Practice Area Directory",
    "Statutory Compliance Calendar",
    "Mega Corporate Skyline Footer",
  ],
  sections: [
    {
      id: "hero",
      type: "hero",
      label: "Hero Banner",
      description: "Service headline, pricing strip, checkmarks & consultation callback card",
      editorKey: "hero",
      required: true,
      defaultEnabled: true,
    },
    {
      id: "services",
      type: "services",
      label: "Services & Practice Areas",
      description: "Filterable category cards, scopes and popular badges",
      editorKey: "services",
      defaultEnabled: true,
    },
    {
      id: "tax-calendar",
      type: "tax-calendar",
      label: "Statutory Due Dates",
      description: "Comprehensive due date tracker with reminder triggers",
      editorKey: "tax-calendar",
      defaultEnabled: true,
    },
    {
      id: "calculators",
      type: "calculators",
      label: "Financial Calculators",
      description: "GST input credit, regime comparator & advance tax tools",
      editorKey: "calculators",
      defaultEnabled: true,
    },
    {
      id: "testimonials",
      type: "testimonials",
      label: "Client Endorsements",
      description: "Client satisfaction metrics and verified endorsements",
      editorKey: "testimonials",
      defaultEnabled: true,
    },
    {
      id: "cta",
      type: "cta",
      label: "Call to Action Banner",
      description: "Pre-footer skyline consultation conversion banner",
      editorKey: "cta",
      defaultEnabled: true,
    },
    {
      id: "contact",
      type: "contact",
      label: "Contact Information Desk",
      description: "Lead form, branch address, contact channels & office directions",
      editorKey: "contact",
      required: true,
      defaultEnabled: true,
    },
  ],
};

